import { DonationImpact } from "@shared/schema";

// This is a placeholder that simulates what we'd do with a real LLM API
// In a production environment, this would call an actual LLM API service
export async function generateCreativeComparisons(impact: DonationImpact): Promise<DonationImpact> {
  // Create a copy of the impact to enrich with creative comparisons
  const enrichedImpact = { ...impact };

  // Generate creative comparisons based on the food rescued amount
  if (impact.foodRescued > 0) {
    // For now we'll use predefined comparisons based on ranges
    // In a real implementation, this would be generated by an LLM
    if (impact.foodRescued < 100) {
      enrichedImpact.babyElephants = "about half a baby elephant";
      enrichedImpact.bison = "nearly one bison";
      enrichedImpact.cars = "about 1/20th of a car";
    } else if (impact.foodRescued < 500) {
      enrichedImpact.babyElephants = `${Math.round(impact.foodRescued / 200)} baby elephants`;
      enrichedImpact.bison = `${Math.round(impact.foodRescued / 100)} bison`;
      enrichedImpact.cars = `${(impact.foodRescued / 4000).toFixed(1)} cars`;
    } else if (impact.foodRescued < 1000) {
      enrichedImpact.babyElephants = `a small herd of ${Math.round(impact.foodRescued / 200)} baby elephants`;
      enrichedImpact.bison = `a group of ${Math.round(impact.foodRescued / 100)} bison roaming the plains`;
      enrichedImpact.cars = `${(impact.foodRescued / 4000).toFixed(1)} compact cars stacked on top of each other`;
    } else {
      enrichedImpact.babyElephants = `an impressive herd of ${Math.round(impact.foodRescued / 200)} baby elephants`;
      enrichedImpact.bison = `a majestic herd of ${Math.round(impact.foodRescued / 100)} bison`;
      enrichedImpact.cars = `${(impact.foodRescued / 4000).toFixed(1)} family cars in a row`;
    }
  }

  // Generate creative descriptions for people fed
  if (impact.mealsProvided > 0) {
    const peopleServed = impact.peopleServed;
    
    if (peopleServed < 10) {
      enrichedImpact.peopleFed = `a family of ${peopleServed}`;
    } else if (peopleServed < 50) {
      enrichedImpact.peopleFed = `everyone at a small community gathering (${peopleServed} people)`;
    } else if (peopleServed < 200) {
      enrichedImpact.peopleFed = `an entire school classroom for a month (${peopleServed} students)`;
    } else {
      enrichedImpact.peopleFed = `everyone in a small concert venue (${peopleServed} people)`;
    }
    
    // Calculate days fed from meals
    const avgMealsPerDay = 3;
    const daysOfFood = Math.round(impact.mealsProvided / (peopleServed * avgMealsPerDay));
    
    if (daysOfFood < 1) {
      enrichedImpact.daysFed = "a nutritious meal";
    } else if (daysOfFood === 1) {
      enrichedImpact.daysFed = "a full day of meals";
    } else if (daysOfFood < 7) {
      enrichedImpact.daysFed = `${daysOfFood} days of meals`;
    } else if (daysOfFood < 30) {
      enrichedImpact.daysFed = `${Math.round(daysOfFood / 7)} weeks of meals`;
    } else {
      enrichedImpact.daysFed = `over a month of meals`;
    }
  }

  return enrichedImpact;
}

// In the future, this function would send the impact data to an LLM API
// and receive back unique creative comparisons for each slide
function callLlmApi(prompt: string): string {
  // This would be replaced with an actual API call
  console.log("LLM API call with prompt:", prompt);
  return "LLM generated response would go here";
}